export const CHAPTERS_LIST_REQUEST = "CHAPTERS_LIST_REQUEST";
export const CHAPTERS_LIST_SUCCESS = "CHAPTERS_LIST_SUCCESS";
export const CHAPTERS_LIST_FAIL = "CHAPTERS_LIST_FAIL";

export const CHAPTERS_DETAILS_REQUEST = "CHAPTERS_DETAILS_REQUEST";
export const CHAPTERS_DETAILS_SUCCESS = "CHAPTERS_DETAILS_SUCCESS";
export const CHAPTERS_DETAILS_FAIL = "CHAPTERS_DETAILS_FAIL";
