export const COMICS_LIST_REQUEST = "COMICS_LIST_REQUEST";
export const COMICS_LIST_SUCCESS = "COMICS_LIST_SUCCESS";
export const COMICS_LIST_FAIL = "COMICS_LIST_FAIL";

export const COMICS_DETAILS_REQUEST = "COMICS_DETAILS_REQUEST";
export const COMICS_DETAILS_SUCCESS = "COMICS_DETAILS_SUCCESS";
export const COMICS_DETAILS_FAIL = "COMICS_DETAILS_FAIL";
