# Generated by Django 4.1.5 on 2023-01-07 10:22

import Comics.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True, unique=True)),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True)),
                ('numPages', models.IntegerField(blank=True, default=0, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=3000)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Trash'), (2, '2 - Horrible'), (3, '3 - Terrible'), (4, '4 - Bad'), (5, '5 - OK'), (6, '6 - Watchable'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Perfect'), (10, '10 - Master Piece')], default=1)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='Comics.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(max_length=10000, upload_to=Comics.models.comics_chapters_images_location)),
                ('images_url', models.URLField(blank=True, default=None, max_length=10000, null=True, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comics.chapter')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('unlikes', models.PositiveIntegerField(default=0)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_like', to='Comics.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('title', models.CharField(max_length=2000, unique='slug')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=Comics.models.comics_images_location)),
                ('image_url', models.URLField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=9)),
                ('status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Dropped', 'Dropped'), ('Coming Soon', 'Coming Soon'), ('Hiatus', 'Hiatus')], max_length=100)),
                ('author', models.CharField(blank=True, max_length=1000)),
                ('artist', models.CharField(blank=True, max_length=1000)),
                ('category', models.CharField(blank=True, choices=[('Manhua', 'Manhua'), ('Manhwa', 'Manhwa'), ('Manga', 'Manga')], default=None, max_length=10)),
                ('numChapters', models.IntegerField(blank=True, default=0, null=True)),
                ('serialized', models.CharField(blank=True, max_length=100)),
                ('released', models.CharField(blank=True, max_length=100)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('like_count', models.BigIntegerField(default='0')),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(blank=True, to='Comics.genre')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='comic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Comics.comic'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='pages', to='Comics.page'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ComicsManager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Comics.comic', models.Model),
        ),
    ]
