# Generated by Django 4.1.5 on 2023-01-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='user',
        ),
    ]
