# Generated by Django 4.1.3 on 2022-12-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='numReviews',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='rating',
        ),
        migrations.AddField(
            model_name='chapter',
            name='numPages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
    ]
