# Generated by Django 4.1.3 on 2022-12-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='link',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='url',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='user',
        ),
        migrations.AddField(
            model_name='genre',
            name='comics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comics.comic'),
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
