# Generated by Django 4.1.3 on 2022-12-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='rating',
            field=models.CharField(max_length=20),
        ),
    ]
