# Generated by Django 4.1.3 on 2022-12-14 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['-updated']},
        ),
    ]
