# Generated by Django 4.1.3 on 2022-12-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='image_url',
        ),
        migrations.AddField(
            model_name='comic',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
