# Generated by Django 4.1.3 on 2022-12-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0002_alter_comic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='category',
            field=models.CharField(blank=True, choices=[('Manhua', 'Manhua'), ('Manhwa', 'Manhwa'), ('Manga', 'Manga')], default='Manhwa', max_length=10),
        ),
    ]
