# Generated by Django 4.1.3 on 2022-12-31 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comics', '0002_alter_comic_created_alter_comic_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
