# Generated by Django 4.1.3 on 2022-12-15 00:51

import Comics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0002_remove_comic_image_url_comic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.ImageField(blank=True, upload_to=Comics.models.comics_images_location),
        ),
    ]
