# Generated by Django 4.1.3 on 2022-12-09 17:51

import Comics.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0002_genre_comics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['-updated']},
        ),
        migrations.RemoveField(
            model_name='genre',
            name='comics',
        ),
        migrations.AddField(
            model_name='comic',
            name='numChapters',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='author',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='comic',
            name='category',
            field=models.CharField(choices=[('Manga', 'Manga'), ('Manhua', 'Manhua'), ('Manhwa', 'Manhwa'), ('Comic', 'Comic'), ('Novel', 'Novel')], default='Manhwa', max_length=1000),
        ),
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.ImageField(blank=True, upload_to=Comics.models.comics_images_location),
        ),
        migrations.AlterField(
            model_name='comic',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='comic',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Dropped', 'Dropped'), ('Coming Soon', 'Coming Soon'), ('Hiatus', 'Hiatus')], max_length=100),
        ),
        migrations.AlterField(
            model_name='comic',
            name='title',
            field=models.CharField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='chapters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comics.chapter'),
        ),
        migrations.AlterField(
            model_name='page',
            name='images',
            field=models.ImageField(blank=True, max_length=10000, null=True, upload_to=Comics.models.comics_chapters_images_location),
        ),
        migrations.AlterField(
            model_name='page',
            name='images_url',
            field=models.URLField(max_length=10000),
        ),
    ]
