# Generated by Django 4.1.5 on 2023-01-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0002_remove_comic_numchapters_alter_page_images_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='numChapters',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
