# Generated by Django 4.1.3 on 2022-12-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0002_remove_comic_link_remove_comic_url_remove_comic_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['updated']},
        ),
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['updated']},
        ),
        migrations.AlterField(
            model_name='comic',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
