# Generated by Django 4.1.3 on 2022-12-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0003_alter_comic_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='artist',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='comic',
            name='category',
            field=models.CharField(blank=True, choices=[('Manhua', 'Manhua'), ('Manhwa', 'Manhwa'), ('Manga', 'Manga')], max_length=1000),
        ),
    ]
