# Generated by Django 4.1.3 on 2022-12-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0003_chapter_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='numReviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
