# Generated by Django 4.1.3 on 2022-12-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0003_comic_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={},
        ),
    ]
