# Generated by Django 4.1.5 on 2023-01-07 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comics', '0003_alter_comic_slug_alter_comic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comic',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
