# Generated by Django 4.1.3 on 2022-12-10 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0003_alter_chapter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['-created']},
        ),
    ]
