# Generated by Django 4.1.5 on 2023-01-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0003_comic_numchapters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['-id']},
        ),
    ]
