# Generated by Django 4.1.3 on 2022-12-10 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0004_alter_chapter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['-updated']},
        ),
    ]
