# Generated by Django 4.1.3 on 2022-12-09 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comics', '0004_alter_page_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='user',
        ),
        migrations.AddField(
            model_name='comic',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
