# Generated by Django 4.1.3 on 2022-12-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0004_rename_image_url_comic_image_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='artist',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
