# Generated by Django 4.1.5 on 2023-01-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0004_comic_user_alter_comic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='slug',
            field=models.SlugField(max_length=1000000, null=True, unique=True),
        ),
    ]
