# Generated by Django 4.1.3 on 2022-12-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0005_comic_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['-title']},
        ),
    ]
