# Generated by Django 4.1.3 on 2022-12-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0005_remove_comic_reader_remove_comic_user_comic_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['-title']},
        ),
    ]
