# Generated by Django 4.1.5 on 2023-01-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0005_alter_comic_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['updated', 'created']},
        ),
    ]
