# Generated by Django 4.1.3 on 2023-01-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0005_comic_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='category',
            field=models.CharField(blank=True, choices=[('Manhua', 'Manhua'), ('Manhwa', 'Manhwa'), ('Manga', 'Manga')], default=None, max_length=10),
        ),
    ]
