# Generated by Django 4.1.3 on 2022-12-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0005_alter_genre_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created']},
        ),
    ]
