# Generated by Django 4.1.3 on 2022-12-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0006_alter_comic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['updated', 'created']},
        ),
    ]
