# Generated by Django 4.1.3 on 2022-12-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0006_alter_comic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='slug',
            field=models.SlugField(max_length=2000, null=True, unique=True),
        ),
    ]
