# Generated by Django 4.1.5 on 2023-01-04 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comics', '0006_alter_comic_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='user',
        ),
        migrations.AddField(
            model_name='chapter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
