# Generated by Django 4.1.3 on 2022-12-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0007_alter_chapter_options_alter_comic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
