# Generated by Django 4.1.3 on 2022-12-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0008_alter_comic_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicsManager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Comics.comic',),
        ),
    ]
