# Generated by Django 4.1.5 on 2023-01-04 06:11

import Comics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0008_alter_page_images_alter_page_images_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='images',
            field=models.ImageField(max_length=10000, upload_to=Comics.models.comics_chapters_images_location),
        ),
    ]
