# Generated by Django 4.1.3 on 2022-12-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0008_chapter_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='volume',
            field=models.CharField(default=0, max_length=2000),
        ),
    ]
