# Generated by Django 4.1.5 on 2023-01-04 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0009_alter_page_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='Comics.chapter'),
        ),
    ]
