# Generated by Django 4.1.3 on 2022-12-02 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0009_alter_chapter_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='volume',
        ),
    ]
