# Generated by Django 4.1.3 on 2022-12-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0011_alter_chapter_options_alter_chapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
