# Generated by Django 4.1.3 on 2022-12-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0011_alter_comic_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comicsmanager',
            options={'ordering': ['updated']},
        ),
    ]
