# Generated by Django 4.1.3 on 2022-12-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0012_alter_chapter_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['updated']},
        ),
        migrations.RemoveField(
            model_name='genre',
            name='comics',
        ),
    ]
