# Generated by Django 4.1.3 on 2022-12-17 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0012_alter_comicsmanager_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comicsmanager',
            options={'ordering': ['-updated']},
        ),
    ]
