# Generated by Django 4.1.3 on 2022-12-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0014_alter_comicsmanager_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
