# Generated by Django 4.1.3 on 2022-12-17 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0015_comic_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['updated', '-title']},
        ),
    ]
