# Generated by Django 4.1.3 on 2022-12-17 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0016_alter_comic_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='image_src',
            new_name='image_url',
        ),
    ]
