# Generated by Django 4.1.3 on 2022-12-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0017_rename_image_src_comic_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='release_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
