# Generated by Django 4.1.3 on 2022-12-18 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0019_alter_comic_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['id', 'title']},
        ),
        migrations.AlterModelOptions(
            name='comicsmanager',
            options={},
        ),
    ]
