# Generated by Django 4.1.3 on 2022-12-18 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0020_alter_comic_options_alter_comicsmanager_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['-id', '-title']},
        ),
    ]
