# Generated by Django 4.1.3 on 2022-12-18 14:41

import Comics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0021_alter_comic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='category',
            field=models.CharField(blank=True, choices=[('Manhua', 'Manhua'), ('Manhwa', 'Manhwa'), ('Manga', 'Manga')], max_length=10),
        ),
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', upload_to=Comics.models.comics_images_location),
        ),
        migrations.AlterField(
            model_name='comic',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='slug',
            field=models.SlugField(blank=True, max_length=2000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Dropped', 'Dropped'), ('Coming Soon', 'Coming Soon'), ('Hiatus', 'Hiatus')], max_length=100),
        ),
    ]
