# Generated by Django 4.1.3 on 2022-12-18 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comics', '0022_alter_comic_category_alter_comic_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='reader',
            field=models.ManyToManyField(blank=True, related_name='readers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comic',
            name='user',
        ),
        migrations.AddField(
            model_name='comic',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
