comics = [
    {
        "id": 137,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Your Talent is Mine",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/07/Cover-1-218x300.jpg",
        "rating": "9.50",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/your-talent-is-mine/',)",
        "updated": "2022-10-10T19:24:34.912168Z",
        "created": "2022-10-10T19:09:22.985641Z"
    },
    {
        "id": 136,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Youngest Scion of the Mages",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/10/resource-1.jpeg",
        "rating": "9.40",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/youngest-scion-of-the-mages/',)",
        "updated": "2022-10-10T19:09:22.971320Z",
        "created": "2022-10-10T19:09:22.971443Z"
    },
    {
        "id": 135,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Worthless Regression",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/03/Worthless_New.jpg",
        "rating": "9.70",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/worthless-regression/',)",
        "updated": "2022-10-10T19:09:22.956577Z",
        "created": "2022-10-10T19:09:22.956699Z"
    },
    {
        "id": 134,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Worn and Torn Newbie",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2020/11/cover-worn.jpg",
        "rating": "9.50",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/worn-and-torn-newbie/',)",
        "updated": "2022-10-10T19:09:22.938712Z",
        "created": "2022-10-10T19:09:22.938867Z"
    },
    {
        "id": 133,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Warrior High School – Dungeon Raid Department",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/10/resource.jpg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/warrior-high-school-dungeon-raid-course/',)",
        "updated": "2022-10-10T19:09:22.918708Z",
        "created": "2022-10-10T19:09:22.918832Z"
    },
    {
        "id": 132,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Wandering Warrior of Wudang",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/09/wanderingwarriorofwudangcover-222x300.png",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/wandering-warrior-of-wudang/',)",
        "updated": "2022-10-10T19:09:22.903178Z",
        "created": "2022-10-10T19:09:22.903300Z"
    },
    {
        "id": 131,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Villain To Kill",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/02/villain.jpg",
        "rating": "9.40",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/villain-to-kill/',)",
        "updated": "2022-10-10T19:09:22.887985Z",
        "created": "2022-10-10T19:09:22.888112Z"
    },
    {
        "id": 130,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Updater",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/03/resource-222x300.png",
        "rating": "8.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/updater/',)",
        "updated": "2022-10-10T19:09:22.872708Z",
        "created": "2022-10-10T19:09:22.872859Z"
    },
    {
        "id": 129,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Ultra Alter",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/09/ultraafter.jpg",
        "rating": "9.10",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/ultra-alter/',)",
        "updated": "2022-10-10T19:09:22.856622Z",
        "created": "2022-10-10T19:09:22.856713Z"
    },
    {
        "id": 128,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Trash of the Count’s Family",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/04/trash.jpg",
        "rating": "10.00",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/trash-of-the-counts-family/',)",
        "updated": "2022-10-10T19:09:22.842123Z",
        "created": "2022-10-10T19:09:22.842212Z"
    },
    {
        "id": 127,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Transmigrating to the Otherworld Once More",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/04/TransmigratingtotheOtherworldOnceMoreCover02_copy2.png",
        "rating": "9.50",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/transmigrating-to-the-otherworld-once-more/',)",
        "updated": "2022-10-10T19:09:22.828984Z",
        "created": "2022-10-10T19:09:22.829074Z"
    },
    {
        "id": 126,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "To Hell With Being A Saint, I’m A Doctor",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/05/saintdoctorCover05.png",
        "rating": "9.50",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/to-hell-with-being-a-saint-im-a-doctor/',)",
        "updated": "2022-10-10T19:09:22.811059Z",
        "created": "2022-10-10T19:09:22.811203Z"
    },
    {
        "id": 125,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Tiger’s Descent",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/06/resource.jpg",
        "rating": "8.70",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/tigers-descent/',)",
        "updated": "2022-10-10T19:09:22.798442Z",
        "created": "2022-10-10T19:09:22.798478Z"
    },
    {
        "id": 124,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The World After The End",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/02/the-world-after-the-end-cover-207x300.jpg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-world-after-the-end/',)",
        "updated": "2022-10-10T19:09:22.788066Z",
        "created": "2022-10-10T19:09:22.788101Z"
    },
    {
        "id": 123,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Tutorial Tower of the Advanced Player",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/02/TutorialAdvancedCover01-200x300.png",
        "rating": "8.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-tutorial-tower-of-the-advanced-player/',)",
        "updated": "2022-10-10T19:09:22.774982Z",
        "created": "2022-10-10T19:09:22.775020Z"
    },
    {
        "id": 122,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Tutorial is Too Hard",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/01/TheTutorialisTooHardCover02.png",
        "rating": "8.70",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-tutorial-is-too-hard/',)",
        "updated": "2022-10-10T19:09:22.764701Z",
        "created": "2022-10-10T19:09:22.764762Z"
    },
    {
        "id": 121,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Time of the Terminally ill Extra",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/11/TerminallyillExtraCover01-222x300.jpg",
        "rating": "8.00",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-time-of-the-terminally-ill-extra/',)",
        "updated": "2022-10-10T19:09:22.754293Z",
        "created": "2022-10-10T19:09:22.754327Z"
    },
    {
        "id": 120,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Strongest Player",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/11/strongestplayer-208x300.gif",
        "rating": "9.50",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/the-strongest-player/',)",
        "updated": "2022-10-10T19:09:21.368551Z",
        "created": "2022-10-10T19:09:21.368689Z"
    },
    {
        "id": 119,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Star of a Supreme Ruler",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/02/resource-1-1-222x300.jpg",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-star-of-a-supreme-ruler/',)",
        "updated": "2022-10-10T19:09:21.353215Z",
        "created": "2022-10-10T19:09:21.353318Z"
    },
    {
        "id": 118,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Second Coming of Gluttony",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/02/the_second_coming_of_gluttony-222x300.jpg",
        "rating": "9.20",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-second-coming-of-gluttony/',)",
        "updated": "2022-10-10T19:09:21.338525Z",
        "created": "2022-10-10T19:09:21.338629Z"
    },
    {
        "id": 117,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The S-Classes That I Raised",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/11/thesclassesthatiraisedcover-212x300.jpg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-s-classes-that-i-raised/',)",
        "updated": "2022-10-10T19:09:21.324455Z",
        "created": "2022-10-10T19:09:21.324595Z"
    },
    {
        "id": 116,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Return of the Crazy Demon",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/07/Crazy_Demon_Cover-207x300.jpg",
        "rating": "9.70",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-return-of-the-crazy-demon/',)",
        "updated": "2022-10-10T19:09:21.306460Z",
        "created": "2022-10-10T19:09:21.306600Z"
    },
    {
        "id": 115,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Novel’s Extra (Remake)",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/06/novelextraCover01.png",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-novels-extra-remake/',)",
        "updated": "2022-10-10T19:09:21.290699Z",
        "created": "2022-10-10T19:09:21.290835Z"
    },
    {
        "id": 114,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Newbie is Too Strong",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/06/Strong_Newbie_Cover.jpg",
        "rating": "9.50",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-newbie-is-too-strong/',)",
        "updated": "2022-10-10T19:09:21.275174Z",
        "created": "2022-10-10T19:09:21.275320Z"
    },
    {
        "id": 113,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Max Level Hero has Returned!",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2020/10/maxlevelheroCover01-222x300.png",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-max-level-hero-has-returned/',)",
        "updated": "2022-10-10T19:09:21.257197Z",
        "created": "2022-10-10T19:09:21.257304Z"
    },
    {
        "id": 112,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Lord’s Coins Aren’t Decreasing?!",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/04/Cover-2-212x300.jpg",
        "rating": "9.30",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-lords-coins-arent-decreasing/',)",
        "updated": "2022-10-10T19:09:21.242969Z",
        "created": "2022-10-10T19:09:21.243073Z"
    },
    {
        "id": 111,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Live",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/04/thelive.jpg",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-live/',)",
        "updated": "2022-10-10T19:09:21.227732Z",
        "created": "2022-10-10T19:09:21.227844Z"
    },
    {
        "id": 110,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The King’s Avatar",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2020/09/47754-211x300.jpeg",
        "rating": "10.00",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/the-kings-avatar/',)",
        "updated": "2022-10-10T19:09:21.213583Z",
        "created": "2022-10-10T19:09:21.213761Z"
    },
    {
        "id": 109,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The King Of Bugs",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/03/Cover-225x300.png",
        "rating": "8.90",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/the-king-of-bug/',)",
        "updated": "2022-10-10T19:09:21.197592Z",
        "created": "2022-10-10T19:09:21.197701Z"
    },
    {
        "id": 108,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Immortal Emperor Luo Wuji Has Returned",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/01/Title_v.2-225x300.jpg",
        "rating": "8.40",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/the-immortal-emperor-luo-wuji-has-returned/',)",
        "updated": "2022-10-10T19:09:21.179180Z",
        "created": "2022-10-10T19:09:21.179403Z"
    },
    {
        "id": 107,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Hero Returns",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/03/hero-returns.jpg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-hero-returns/',)",
        "updated": "2022-10-10T19:09:21.163825Z",
        "created": "2022-10-10T19:09:21.163981Z"
    },
    {
        "id": 106,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Heavenly Demon Can’t Live a Normal Life",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/06/sogdo-is-depressed.jpg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-heavenly-demon-cant-live-a-normal-life/',)",
        "updated": "2022-10-10T19:09:21.146323Z",
        "created": "2022-10-10T19:09:21.146480Z"
    },
    {
        "id": 105,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Greatest Estate Developer",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/09/EstateDevCover01.png",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-greatest-estate-developer/',)",
        "updated": "2022-10-10T19:09:21.129600Z",
        "created": "2022-10-10T19:09:21.129701Z"
    },
    {
        "id": 104,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The God of Pro Wrestling",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/04/resource-4-222x300.jpg",
        "rating": "9.50",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-god-of-pro-wrestling/',)",
        "updated": "2022-10-10T19:09:21.111298Z",
        "created": "2022-10-10T19:09:21.111407Z"
    },
    {
        "id": 103,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Game That I Came From",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/03/Cover-1-226x300.jpg",
        "rating": "9.00",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/the-game-that-i-came-from/',)",
        "updated": "2022-10-10T19:09:21.096838Z",
        "created": "2022-10-10T19:09:21.096988Z"
    },
    {
        "id": 102,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Frenzy Of Evolution",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/11/cover2.jpg",
        "rating": "9.00",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/the-frenzy-of-evolution/',)",
        "updated": "2022-10-10T19:09:21.081944Z",
        "created": "2022-10-10T19:09:21.082047Z"
    },
    {
        "id": 101,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The First Order",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/10/The-First-Order-225x300.png",
        "rating": "8.70",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/the-first-order/',)",
        "updated": "2022-10-10T19:09:21.056579Z",
        "created": "2022-10-10T19:09:21.056611Z"
    },
    {
        "id": 100,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Dark Magician Transmigrates After 66666 Years",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/06/666666.jpg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-dark-magician-transmigrates-after-66666-years/',)",
        "updated": "2022-10-10T19:09:19.801849Z",
        "created": "2022-10-10T19:09:19.802001Z"
    },
    {
        "id": 99,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Constellation That Returned From Hell",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/04/kapkaw-copy-222x300.jpg",
        "rating": "9.40",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-constellation-that-returned-from-hell/',)",
        "updated": "2022-10-10T19:09:19.785588Z",
        "created": "2022-10-10T19:09:19.785697Z"
    },
    {
        "id": 98,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Challenger",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/09/Title-Cover-1.jpg",
        "rating": "9.00",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-challenger/',)",
        "updated": "2022-10-10T19:09:19.770310Z",
        "created": "2022-10-10T19:09:19.770412Z"
    },
    {
        "id": 97,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "The Book of Lagier",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/07/bookoflagiercover.png",
        "rating": "8.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/the-book-of-lagier/',)",
        "updated": "2022-10-10T19:09:19.755899Z",
        "created": "2022-10-10T19:09:19.755998Z"
    },
    {
        "id": 96,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Taming Master",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2020/11/TamingMasterCover06-222x300.png",
        "rating": "10.00",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/taming-master/',)",
        "updated": "2022-10-10T19:09:19.736813Z",
        "created": "2022-10-10T19:09:19.736976Z"
    },
    {
        "id": 95,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Talent-Swallowing Magician",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/12/talentswallowing.jpg",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/talent-swallowing-magician/',)",
        "updated": "2022-10-10T19:09:19.720916Z",
        "created": "2022-10-10T19:09:19.721049Z"
    },
    {
        "id": 94,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Swordmaster’s Youngest Son",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/04/cover.jpg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/swordmasters-youngest-son/',)",
        "updated": "2022-10-10T19:09:19.706374Z",
        "created": "2022-10-10T19:09:19.706462Z"
    },
    {
        "id": 93,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Sword Fanatic Wanders Through The Night",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/06/swordfanaticCover01.png",
        "rating": "9.70",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/sword-fanatic-wanders-through-the-night/',)",
        "updated": "2022-10-10T19:09:19.692622Z",
        "created": "2022-10-10T19:09:19.692710Z"
    },
    {
        "id": 92,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Super Evolution",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/07/super-e1633947550578-207x300.png",
        "rating": "8.80",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/super-evolution/',)",
        "updated": "2022-10-10T19:09:19.678391Z",
        "created": "2022-10-10T19:09:19.678509Z"
    },
    {
        "id": 91,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Starting Today, I’m a Player",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/09/Starting-Today-Im-a-Player-222x300.png",
        "rating": "9.10",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/starting-today-im-a-player/',)",
        "updated": "2022-10-10T19:09:19.662697Z",
        "created": "2022-10-10T19:09:19.662824Z"
    },
    {
        "id": 90,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Standard of Reincarnation",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/08/standardofReCover03.png",
        "rating": "9.70",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/standard-of-reincarnation/',)",
        "updated": "2022-10-10T19:09:19.647480Z",
        "created": "2022-10-10T19:09:19.647573Z"
    },
    {
        "id": 89,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "SSS-Class Suicide Hunter",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2020/12/sss.jpg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/sss-class-suicide-hunter/',)",
        "updated": "2022-10-10T19:09:19.628880Z",
        "created": "2022-10-10T19:09:19.628978Z"
    },
    {
        "id": 88,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "SSS-Class Gacha Hunter",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/09/Illustration3.png",
        "rating": "9.50",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/sss-class-gacha-hunter/',)",
        "updated": "2022-10-10T19:09:19.608214Z",
        "created": "2022-10-10T19:09:19.608334Z"
    },
    {
        "id": 87,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Spirit Farmer",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2020/10/poster022-222x300.jpg",
        "rating": "9.40",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/spirit-farmer/',)",
        "updated": "2022-10-10T19:09:19.593319Z",
        "created": "2022-10-10T19:09:19.593408Z"
    },
    {
        "id": 86,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Solo Spell Caster",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2020/11/logo-asura-222x300.jpg",
        "rating": "8.30",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/solo-spell-caster/',)",
        "updated": "2022-10-10T19:09:19.578345Z",
        "created": "2022-10-10T19:09:19.578434Z"
    },
    {
        "id": 85,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Solo Max-Level Newbie",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/07/solomaxlevelnewbie.jpg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/solo-max-level-newbie/',)",
        "updated": "2022-10-10T19:09:19.562707Z",
        "created": "2022-10-10T19:09:19.562795Z"
    },
    {
        "id": 84,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Solo Leveling",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/03/Solo_Leveling_Title_Cover_-_Barak-222x300.jpg",
        "rating": "9.30",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/solo-leveling/',)",
        "updated": "2022-10-10T19:09:19.548036Z",
        "created": "2022-10-10T19:09:19.548181Z"
    },
    {
        "id": 83,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Solo Bug Player",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/02/cover4-205x300.gif",
        "rating": "8.70",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/solo-bug-player/',)",
        "updated": "2022-10-10T19:09:19.532608Z",
        "created": "2022-10-10T19:09:19.532713Z"
    },
    {
        "id": 82,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Sleeping Ranker",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/03/resource-2-1.jpg",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/sleeping-ranker/',)",
        "updated": "2022-10-10T19:09:19.517588Z",
        "created": "2022-10-10T19:09:19.517676Z"
    },
    {
        "id": 81,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Shenwu Tianzun",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2020/11/48778-225x300.jpg",
        "rating": "7.60",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/shenwu-tianzun/',)",
        "updated": "2022-10-10T19:09:19.488745Z",
        "created": "2022-10-10T19:09:19.488777Z"
    },
    {
        "id": 80,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Shadowless Night",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/08/ShadowlessNightCover03-1.png",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/shadowless-night/',)",
        "updated": "2022-10-10T19:09:18.197212Z",
        "created": "2022-10-10T19:09:18.197301Z"
    },
    {
        "id": 79,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Saving the Villain Who was Abandoned by the Female Lead **Dropped**",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2020/10/50651-178x300.jpg",
        "rating": "9.00",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/saving-the-villain-who-was-abandoned-by-the-female-lead/',)",
        "updated": "2022-10-10T19:09:18.182350Z",
        "created": "2022-10-10T19:09:18.182465Z"
    },
    {
        "id": 78,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Rise of The Cheat User",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/10/capa.jpg",
        "rating": "8.50",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/rise-of-the-cheat-user/',)",
        "updated": "2022-10-10T19:09:18.166273Z",
        "created": "2022-10-10T19:09:18.166410Z"
    },
    {
        "id": 77,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Rise From The Rubble",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/04/rise.jpg",
        "rating": "9.30",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/rise-from-the-rubble/',)",
        "updated": "2022-10-10T19:09:18.151722Z",
        "created": "2022-10-10T19:09:18.151817Z"
    },
    {
        "id": 76,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Return of The Unrivaled Spear Knight",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/05/cover9.jpg",
        "rating": "9.70",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/return-of-the-unrivaled-spear-knight/',)",
        "updated": "2022-10-10T19:09:18.136133Z",
        "created": "2022-10-10T19:09:18.136269Z"
    },
    {
        "id": 75,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Return of the SSS-Class Ranker",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/08/ReturnSSSCover01.png",
        "rating": "9.60",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/return-of-the-sss-class-ranker/',)",
        "updated": "2022-10-10T19:09:18.117231Z",
        "created": "2022-10-10T19:09:18.117323Z"
    },
    {
        "id": 74,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Return Of The Shattered Constellation",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/11/unknown.png",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/return-of-the-shattered-constellation/',)",
        "updated": "2022-10-10T19:09:18.103557Z",
        "created": "2022-10-10T19:09:18.103701Z"
    },
    {
        "id": 73,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Return of the Mount Hua Sect",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/03/cover.jpg",
        "rating": "10.00",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/return-of-the-mount-hua-sect/',)",
        "updated": "2022-10-10T19:09:18.089819Z",
        "created": "2022-10-10T19:09:18.089912Z"
    },
    {
        "id": 72,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Return of the Disaster-Class Hero",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/10/DisasterheroCover01.png",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/return-of-the-disaster-class-hero/',)",
        "updated": "2022-10-10T19:09:18.075976Z",
        "created": "2022-10-10T19:09:18.076068Z"
    },
    {
        "id": 71,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Return of the 8th Class Magician",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/07/8thclass.jpg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/return-of-the-8th-class-magician/',)",
        "updated": "2022-10-10T19:09:18.059318Z",
        "created": "2022-10-10T19:09:18.059408Z"
    },
    {
        "id": 70,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Reincarnation of the Suicidal Battle God",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/06/sogdobogdo.jpg",
        "rating": "10.00",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/reincarnation-of-the-suicidal-battle-god/',)",
        "updated": "2022-10-10T19:09:18.045498Z",
        "created": "2022-10-10T19:09:18.045626Z"
    },
    {
        "id": 69,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Reincarnation Of The Strongest Sword God",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/08/SwordGodCover01.png",
        "rating": "9.30",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/reincarnation-of-the-strongest-sword-god/',)",
        "updated": "2022-10-10T19:09:18.031590Z",
        "created": "2022-10-10T19:09:18.031735Z"
    },
    {
        "id": 68,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Reincarnated Escort Warrior",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/07/Untitled-1.jpg",
        "rating": "9.70",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/reincarnated-escort-warrior/',)",
        "updated": "2022-10-10T19:09:18.014780Z",
        "created": "2022-10-10T19:09:18.014871Z"
    },
    {
        "id": 67,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Regressor Instruction Manual",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/10/regressor-cover-222x300.jpg",
        "rating": "10.00",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/regressor-instruction-manual/',)",
        "updated": "2022-10-10T19:09:17.999179Z",
        "created": "2022-10-10T19:09:17.999268Z"
    },
    {
        "id": 66,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Reformation of the Deadbeat Noble",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/05/Cover1-3-210x300.png",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/reformation-of-the-deadbeat-noble/',)",
        "updated": "2022-10-10T19:09:17.985133Z",
        "created": "2022-10-10T19:09:17.985296Z"
    },
    {
        "id": 65,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Reaper of the Drifting Moon",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/07/Reaper-Moon-Cover-Animation_Compressed.gif",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/reaper-of-the-drifting-moon/',)",
        "updated": "2022-10-10T19:09:17.970622Z",
        "created": "2022-10-10T19:09:17.970710Z"
    },
    {
        "id": 64,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Player Who Returned 10,000 Years Later",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/07/Player10000yearsCover02_copy.png",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/player-who-returned-10000-years-later/',)",
        "updated": "2022-10-10T19:09:17.956773Z",
        "created": "2022-10-10T19:09:17.956862Z"
    },
    {
        "id": 63,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Player Who Can’t Level Up",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/02/Player_That_Cant_Level_Up_Title_Card_-_Barak_kopya.jpg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/player-who-cant-level-up/',)",
        "updated": "2022-10-10T19:09:17.941546Z",
        "created": "2022-10-10T19:09:17.941636Z"
    },
    {
        "id": 62,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Overpowered Sword",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/06/overpoweredswordCover01.png",
        "rating": "9.60",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/overpowered-sword/',)",
        "updated": "2022-10-10T19:09:17.929883Z",
        "created": "2022-10-10T19:09:17.929918Z"
    },
    {
        "id": 61,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Overbearing Tyrant",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/05/overtyrantCover01.png",
        "rating": "9.70",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/overbearing-tyrant/',)",
        "updated": "2022-10-10T19:09:17.919222Z",
        "created": "2022-10-10T19:09:17.919256Z"
    },
    {
        "id": 60,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "On My Way to Kill God",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/09/resource-1.jpeg",
        "rating": "9.30",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/on-my-way-to-kill-god/',)",
        "updated": "2022-10-10T19:09:16.676312Z",
        "created": "2022-10-10T19:09:16.676403Z"
    },
    {
        "id": 59,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Of All Things, I Became a Crow",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/04/KK.jpg",
        "rating": "9.40",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/of-all-things-i-became-a-crow/',)",
        "updated": "2022-10-10T19:09:16.662422Z",
        "created": "2022-10-10T19:09:16.662512Z"
    },
    {
        "id": 58,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Never Die Extra",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/09/resource.jpg",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/never-die-extra/',)",
        "updated": "2022-10-10T19:09:16.648477Z",
        "created": "2022-10-10T19:09:16.648568Z"
    },
    {
        "id": 57,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "My School Life Pretending To Be a Worthless Person",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/08/myschoollifeCover01.png",
        "rating": "9.70",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/my-school-life-pretending-to-be-a-worthless-person/',)",
        "updated": "2022-10-10T19:09:16.632943Z",
        "created": "2022-10-10T19:09:16.633161Z"
    },
    {
        "id": 56,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "My Path to Killing Gods in Another World",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/06/killinggods.jpg",
        "rating": "8.80",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/my-path-to-killing-gods-in-another-world/',)",
        "updated": "2022-10-10T19:09:16.614131Z",
        "created": "2022-10-10T19:09:16.614225Z"
    },
    {
        "id": 55,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "My Healing Game",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/08/MyHealingGame04.png",
        "rating": "9.20",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/my-healing-game/',)",
        "updated": "2022-10-10T19:09:16.599789Z",
        "created": "2022-10-10T19:09:16.599877Z"
    },
    {
        "id": 54,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "My Daughter is the Final Boss",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/04/daughterbosscover-1.jpg",
        "rating": "9.70",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/my-daughter-is-the-final-boss/',)",
        "updated": "2022-10-10T19:09:16.582242Z",
        "created": "2022-10-10T19:09:16.582330Z"
    },
    {
        "id": 53,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "My Daughter is a Dragon!",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/08/DaughterDragonCover01.png",
        "rating": "9.70",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/my-daughter-is-a-dragon/',)",
        "updated": "2022-10-10T19:09:16.567562Z",
        "created": "2022-10-10T19:09:16.567698Z"
    },
    {
        "id": 52,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "My Civil Servant Life Reborn in the Strange World",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/02/bitchassmofo-379x512.jpg",
        "rating": "9.00",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/my-civil-servant-life-reborn-in-the-strange-world/',)",
        "updated": "2022-10-10T19:09:16.553287Z",
        "created": "2022-10-10T19:09:16.553409Z"
    },
    {
        "id": 51,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Murim Login",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/04/LoginMoorimCover05.png",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/murim-login/',)",
        "updated": "2022-10-10T19:09:16.538572Z",
        "created": "2022-10-10T19:09:16.538693Z"
    },
    {
        "id": 50,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Mookhyang The Origin",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/02/ponytail_boy_-222x300.png",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/mookhyang-the-origin/',)",
        "updated": "2022-10-10T19:09:16.523961Z",
        "created": "2022-10-10T19:09:16.524073Z"
    },
    {
        "id": 49,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Maxed Out Leveling",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/11/resource-1-1-1-222x300.jpg",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/maxed-out-leveling/',)",
        "updated": "2022-10-10T19:09:16.510085Z",
        "created": "2022-10-10T19:09:16.510176Z"
    },
    {
        "id": 48,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Max Level Returner",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2020/10/COVER-ENG-1-222x300.jpg",
        "rating": "10.00",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/max-level-returner/',)",
        "updated": "2022-10-10T19:09:16.493349Z",
        "created": "2022-10-10T19:09:16.493440Z"
    },
    {
        "id": 47,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Legendary Youngest Son of the Marquis House",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/03/legendarymarquis.jpg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/legendary-youngest-son-of-the-marquis-house-manhwa/',)",
        "updated": "2022-10-10T19:09:16.479855Z",
        "created": "2022-10-10T19:09:16.479945Z"
    },
    {
        "id": 46,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Legend of Mir: The Golden Armored Dragon",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2020/12/resource-1-222x300.jpg",
        "rating": "8.00",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/legend-of-mir-the-golden-armored-dragon/',)",
        "updated": "2022-10-10T19:09:16.460311Z",
        "created": "2022-10-10T19:09:16.460401Z"
    },
    {
        "id": 45,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Legend of Asura – The Venom Dragon",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/02/Legend_of_Asura_-_The_Venom_Dragon_Title_Card_-_Barak_New-222x300.jpg",
        "rating": "9.20",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/legend-of-asura-the-venom-dragon/',)",
        "updated": "2022-10-10T19:09:16.444846Z",
        "created": "2022-10-10T19:09:16.444934Z"
    },
    {
        "id": 44,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "King of the Mound",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/07/KingoftheMoundCover01.png",
        "rating": "9.20",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/king-of-the-mound/',)",
        "updated": "2022-10-10T19:09:16.426706Z",
        "created": "2022-10-10T19:09:16.426796Z"
    },
    {
        "id": 43,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "King of Runes",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/01/king-of-runes-1-226x300.jpg",
        "rating": "8.90",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/king-of-runes/',)",
        "updated": "2022-10-10T19:09:16.411282Z",
        "created": "2022-10-10T19:09:16.411371Z"
    },
    {
        "id": 42,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Kill The Dragon",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/04/coverrr.jpg",
        "rating": "9.50",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/kill-the-dragon/',)",
        "updated": "2022-10-10T19:09:16.396930Z",
        "created": "2022-10-10T19:09:16.397021Z"
    },
    {
        "id": 41,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Join Our Discord",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/09/Untitled-1-ii-212x300.jpg",
        "rating": "8.00",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/join-our-discord/',)",
        "updated": "2022-10-10T19:09:16.371219Z",
        "created": "2022-10-10T19:09:16.371259Z"
    },
    {
        "id": 40,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "I’ve Become the Villainous Empress of a Novel",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2020/09/52838-222x300.jpg",
        "rating": "8.50",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/ive-become-the-villainous-empress-of-a-novel/',)",
        "updated": "2022-10-10T19:09:15.092954Z",
        "created": "2022-10-10T19:09:15.093148Z"
    },
    {
        "id": 39,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "I’m the Only One Loved by the Constellations!",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/08/Cover11-222x300.jpg",
        "rating": "9.30",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/im-the-only-one-loved-by-the-constellations/',)",
        "updated": "2022-10-10T19:09:15.078278Z",
        "created": "2022-10-10T19:09:15.078412Z"
    },
    {
        "id": 38,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "I Shall Live As a Prince",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/04/princee-222x300.jpg",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/i-shall-live-as-a-prince/',)",
        "updated": "2022-10-10T19:09:15.063857Z",
        "created": "2022-10-10T19:09:15.063960Z"
    },
    {
        "id": 37,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "I Reincarnated As The Crazed Heir",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/07/Title-Cover-kopya.png",
        "rating": "9.20",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/i-reincarnated-as-the-crazed-heir/',)",
        "updated": "2022-10-10T19:09:15.046703Z",
        "created": "2022-10-10T19:09:15.046809Z"
    },
    {
        "id": 36,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "I Regressed As The Duke",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/04/unknown_1-1.png",
        "rating": "9.20",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/i-regressed-as-the-duke/',)",
        "updated": "2022-10-10T19:09:15.027924Z",
        "created": "2022-10-10T19:09:15.028027Z"
    },
    {
        "id": 35,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "I Obtained a Mythic Item",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/06/IObtainedaMythicItemCover04.png",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/i-obtained-a-mythic-item/',)",
        "updated": "2022-10-10T19:09:15.012624Z",
        "created": "2022-10-10T19:09:15.012728Z"
    },
    {
        "id": 34,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "I Grow Stronger By Eating!",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/05/IMG_8074.png",
        "rating": "9.00",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/i-grow-stronger-by-eating/',)",
        "updated": "2022-10-10T19:09:14.996580Z",
        "created": "2022-10-10T19:09:14.996684Z"
    },
    {
        "id": 33,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "I Became a Renowned Family’s Sword Prodigy",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/06/swordprodigyCover02.png",
        "rating": "8.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/i-became-a-renowned-familys-sword-prodigy/',)",
        "updated": "2022-10-10T19:09:14.982539Z",
        "created": "2022-10-10T19:09:14.982680Z"
    },
    {
        "id": 32,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "I Am the Fated Villain",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/11/fatedvillain-2.jpg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/i-am-the-fated-villain/',)",
        "updated": "2022-10-10T19:09:14.965703Z",
        "created": "2022-10-10T19:09:14.965858Z"
    },
    {
        "id": 31,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "How To Live As a Villain",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/11/liveasvillain.jpg",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/how-to-live-as-a-villain/',)",
        "updated": "2022-10-10T19:09:14.948466Z",
        "created": "2022-10-10T19:09:14.948568Z"
    },
    {
        "id": 30,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Hoarding in Hell",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/05/cover2.jpg",
        "rating": "9.50",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/hoarding-in-hell/',)",
        "updated": "2022-10-10T19:09:14.933667Z",
        "created": "2022-10-10T19:09:14.933862Z"
    },
    {
        "id": 29,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Hero Has Returned",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/06/heroc-2-1-225x300.png",
        "rating": "9.50",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/hero-has-returned/',)",
        "updated": "2022-10-10T19:09:14.916638Z",
        "created": "2022-10-10T19:09:14.916728Z"
    },
    {
        "id": 28,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Helmut: The Forsaken Child",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/08/helmutCover01.png",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/helmut-the-forsaken-child/',)",
        "updated": "2022-10-10T19:09:14.903969Z",
        "created": "2022-10-10T19:09:14.904039Z"
    },
    {
        "id": 27,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Heavenly Sword’s Grand Saga",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/06/grandSagaCover02.png",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/heavenly-swords-grand-saga/',)",
        "updated": "2022-10-10T19:09:14.892468Z",
        "created": "2022-10-10T19:09:14.892517Z"
    },
    {
        "id": 26,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Heavenly Martial God",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/09/martialgod.jpg",
        "rating": "9.30",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/heavenly-martial-god/',)",
        "updated": "2022-10-10T19:09:14.881716Z",
        "created": "2022-10-10T19:09:14.881753Z"
    },
    {
        "id": 25,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Heavenly Demon Instructor",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/12/heavenlydemoninstructor-1-225x300.jpg",
        "rating": "9.60",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/heavenly-demon-instructor/',)",
        "updated": "2022-10-10T19:09:14.871251Z",
        "created": "2022-10-10T19:09:14.871304Z"
    },
    {
        "id": 24,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Genius of the Unique Lineage",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/08/geniusLineageCover01.png",
        "rating": "9.50",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/genius-of-the-unique-lineage/',)",
        "updated": "2022-10-10T19:09:14.860273Z",
        "created": "2022-10-10T19:09:14.860309Z"
    },
    {
        "id": 23,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "For My Forsaken Beloved",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/05/unknown-4.png",
        "rating": "9.20",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/for-my-forsaken-beloved/',)",
        "updated": "2022-10-10T19:09:14.849891Z",
        "created": "2022-10-10T19:09:14.849928Z"
    },
    {
        "id": 22,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Existence",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/08/kitaresourceimg.jpeg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/existence/',)",
        "updated": "2022-10-10T19:09:14.838747Z",
        "created": "2022-10-10T19:09:14.838799Z"
    },
    {
        "id": 21,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Ending Maker",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/05/ending_maker_01.jpg",
        "rating": "9.70",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/ending-maker/',)",
        "updated": "2022-10-10T19:09:14.813821Z",
        "created": "2022-10-10T19:09:14.813852Z"
    },
    {
        "id": 20,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Emperor’s Domination",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/03/f3556622c9ac203f7800dd88f8efe81126b1bbf8-225x300.jpg",
        "rating": "9.00",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/emperors-domination/',)",
        "updated": "2022-10-10T19:09:13.626380Z",
        "created": "2022-10-10T19:09:13.626473Z"
    },
    {
        "id": 19,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Dungeon Odyssey",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/09/resource-2.jpeg",
        "rating": "9.70",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/dungeon-odyssey/',)",
        "updated": "2022-10-10T19:09:13.609264Z",
        "created": "2022-10-10T19:09:13.609445Z"
    },
    {
        "id": 18,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Dukedom’s Legendary Prodigy",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/05/resource-1.png",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/dukedoms-legendary-prodigy/',)",
        "updated": "2022-10-10T19:09:13.595712Z",
        "created": "2022-10-10T19:09:13.595804Z"
    },
    {
        "id": 17,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Duke Pendragon",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/12/Illustration3.jpg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/duke-pendragon/',)",
        "updated": "2022-10-10T19:09:13.581275Z",
        "created": "2022-10-10T19:09:13.581391Z"
    },
    {
        "id": 16,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Drug Devourer",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/10/B38E4B6F-2931-4750-AA97-2D13C489F774.jpeg",
        "rating": "9.50",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/drug-devourer/',)",
        "updated": "2022-10-10T19:09:13.560978Z",
        "created": "2022-10-10T19:09:13.561102Z"
    },
    {
        "id": 15,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Doctor’s Rebirth",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/01/doctors-rebirth-cover-222x300.jpg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/doctors-rebirth/',)",
        "updated": "2022-10-10T19:09:13.545652Z",
        "created": "2022-10-10T19:09:13.545742Z"
    },
    {
        "id": 14,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Demonic Spirit King",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/11/DemonicSpiritKing-209x300.jpg",
        "rating": "9.60",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/demonic-spirit-king/',)",
        "updated": "2022-10-10T19:09:13.532028Z",
        "created": "2022-10-10T19:09:13.532159Z"
    },
    {
        "id": 13,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Demon in Mount Hua",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/07/demonmounthuaCover01.png",
        "rating": "9.50",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/demon-in-mount-hua/',)",
        "updated": "2022-10-10T19:09:13.518561Z",
        "created": "2022-10-10T19:09:13.518652Z"
    },
    {
        "id": 12,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Death Is the Only Ending for the Villainess",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2020/10/IMG_8700.png",
        "rating": "9.40",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/death-is-the-only-ending-for-the-villainess/',)",
        "updated": "2022-10-10T19:09:13.505521Z",
        "created": "2022-10-10T19:09:13.505612Z"
    },
    {
        "id": 11,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Damn Reincarnation",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/06/Damn_ReincarnationCover003.png",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/damn-reincarnation/',)",
        "updated": "2022-10-10T19:09:13.491007Z",
        "created": "2022-10-10T19:09:13.491100Z"
    },
    {
        "id": 10,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Chronicles Of The Martial God’s Return",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/05/martialreturnCover01.png",
        "rating": "9.60",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/chronicles-of-the-martial-gods-return/',)",
        "updated": "2022-10-10T19:09:13.476979Z",
        "created": "2022-10-10T19:09:13.477068Z"
    },
    {
        "id": 9,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Champion’s Path to Murim",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/09/PathtoMurimCover01.png",
        "rating": "9.60",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/champions-path-to-murim/',)",
        "updated": "2022-10-10T19:09:13.462936Z",
        "created": "2022-10-10T19:09:13.463025Z"
    },
    {
        "id": 8,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Carnivorous Hunter",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/07/CarniHunterColor02.png",
        "rating": "9.40",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/carnivorous-hunter/',)",
        "updated": "2022-10-10T19:09:13.445175Z",
        "created": "2022-10-10T19:09:13.445264Z"
    },
    {
        "id": 7,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Barbarian Quest",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/04/BarbQuest_hElookkindadumbaf-1.jpg",
        "rating": "9.90",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/barbarian-quest/',)",
        "updated": "2022-10-10T19:09:13.430972Z",
        "created": "2022-10-10T19:09:13.431071Z"
    },
    {
        "id": 6,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Archmage Transcending Through Regression",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/10/resource.jpeg",
        "rating": "9.80",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/archmage-transcending-through-regression/',)",
        "updated": "2022-10-10T19:09:13.417517Z",
        "created": "2022-10-10T19:09:13.417605Z"
    },
    {
        "id": 5,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Arcana Fantasy",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2020/12/tall-225x300.jpg",
        "rating": "8.00",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/arcana-fantasy/',)",
        "updated": "2022-10-10T19:09:13.404618Z",
        "created": "2022-10-10T19:09:13.404735Z"
    },
    {
        "id": 4,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Academy’s Undercover Professor",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/06/Academys_Undercover_ProfessorCover_copy.png",
        "rating": "9.70",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/academys-undercover-professor/',)",
        "updated": "2022-10-10T19:09:13.391945Z",
        "created": "2022-10-10T19:09:13.391981Z"
    },
    {
        "id": 3,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Absolute Sword Sense",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/06/swordsenseCover03.png",
        "rating": "9.20",
        "numReviews": 0,
        "genres": "Manhwa",
        "link": "('https://asura.gg/manga/absolute-sword-sense/',)",
        "updated": "2022-10-10T19:09:13.381603Z",
        "created": "2022-10-10T19:09:13.381641Z"
    },
    {
        "id": 2,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "Above the Heavens",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2021/09/abovetheheavenscover-1-207x300.jpg",
        "rating": "9.00",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/above-the-heavens/',)",
        "updated": "2022-10-10T19:09:13.371309Z",
        "created": "2022-10-10T19:09:13.371345Z"
    },
    {
        "id": 1,
        "sources": [],
        "tags": [],
        "chapters": [],
        "user": {
            "username": "",
            "email": ""
        },
        "authors": [],
        "reviews": [],
        "title": "A Comic Artist’s Survival Guide",
        "description": "",
        "image": "https://asura.gg/wp-content/uploads/2022/04/cover1.jpg",
        "rating": "8.00",
        "numReviews": 0,
        "genres": "Manhua",
        "link": "('https://asura.gg/manga/a-comic-artists-survival-guide/',)",
        "updated": "2022-10-10T19:09:13.360807Z",
        "created": "2022-10-10T19:09:13.360845Z"
    }
]
